import { Metadata } from "next";

export const metadata: Metadata = {
    title: "О нас",
    description: "Generated by create next app",
  };
  

export default function Home() {
  return (
    <div>
      О нас
    </div>
  );
}
