import { getMenu } from "@/api/menu";
import { getPage } from "@/api/page";
import { getProducts } from "@/api/product";
import { firstLevelMenu } from "@/helpers/helpers";
import { TopPageComponent } from "@/page-component";
import { Metadata } from "next";
import { notFound, useRouter } from "next/navigation";

// export const metadata: Metadata = {
//     title: "Страница курсов",
//     description: "Generated by create next app",
// };

export async function generateMetadata({ params}: { params: { alias: string } }): Promise<Metadata> {
    const page = await getPage(params.alias);
    return {
        title: page?.metaTitle,
        description: page?.metaDescription,
        openGraph: {
            title: page?.metaTitle,
            description: page?.metaDescription,
            url: process.env.NEXT_PUBLIC_DOMAIN
        }
    }
}

export async function generateStaticParams() {
    let path: { alias: string; }[] = []
    for (const firstLvlRoute of firstLevelMenu) {
        const menu = await getMenu(firstLvlRoute.id);
        path = path.concat(menu.flatMap((item) => item.pages.map((page) => ({ alias: `/${firstLvlRoute.route}/${page.alias}` }))))
    }
    return path
}

export default async function TopPage({ params}: { params: { alias: string } }) {
    const page = await getPage(params.alias);
    if (!page) {
        notFound();
    }

    const products = await getProducts(page.category)

    return <TopPageComponent page={page} firstCategory={page?.firstCategory} products={products} />;
}
